config/routes.rb
Rails.application.routes.draw do
  get 'sessions/logout'

  get 'sessions/login'

  post 'sessions' => 'sessions#create'

  resources :posts do
    resources :comments
  end
  get 'pages/index'
  root 'pages#index'
  get 'registration' => 'users#new', as: 'registration'
  post 'users' => 'users#create'
  get	'like' =>	'posts#like'
  get 'dislike' => 'posts#dislike'
  get 'best' => 'posts#best'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  text       :text
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_presence_of :text
  validates :text, length: {maximum: 140}
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  image      :string
#  rating     :integer
#

class Post < ApplicationRecord
  validates_presence_of :title, :body, :user
  validates_uniqueness_of :title
  validates :title, length: {minimum: 5 ,maximum: 100}
  validates :body, length: {minimum: 10, maximum: 140}


  belongs_to :user

  has_many :tags, dependent: :destroy
  has_many :ratings
  has_many :comments, dependent: :destroy

  mount_uploader :image, PostImageUploader

  scope :newest, -> {order(:created_at).reverse}


end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Rating < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :post_id, uniqueness: {scope: :user_id}

  end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :ratings
  has_many :tags, through: :posts
  has_many :comments

  validates :password_digest, length:{minimum: 6}
  validates_uniqueness_of :email

  ROLES = %w(admin manager user) # все равно, что массив
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_author(user) #передаем юзера, а не поле, которому принадлежит запись и сравниваем с поточным
    user == current_user
  end

  helper_method :current_user, :user_author #хелпер позволяет вызывать метод в других контр. и вьюхах
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_url, notice: 'Comment was successfully created.' }
        format.js { }
      end
    end
    end

    def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
   end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:text)
  end

 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.newest
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    unless user_author(@post.user)
      redirect_to root_path, notice: 'Нет прав доступа'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
        respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    if can_user_vote?
      @post = Post.find(params[:id])
      rating = Rating.new
      rating.user = current_user
      rating.post = @post
      @post.rating = @post.rating.to_i + 1 unless user_author(@post.user)
      rating.save
      @post.save
    end
  end

  def dislike
    if can_user_vote?
      @post = Post.find(params[:id])
      rating = Rating.new
      rating.user = current_user
      rating.post = @post
      @post.rating = @post.rating.to_i - 1 unless user_author(@post.user)
      rating.save
      @post.save
    end
  end

  def best
    @post = Post.all.where("rating >= '10'")
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :rating)
    end

    def can_user_vote?
      @rated_by = Rating.where(user_id: current_user.id, post_id: params[:id])
      @rated_by.blank?
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    @user
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
    else
      redirect_to :back
    end
    redirect_to root_path
  end

  def logout
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name,:email, :password))
    if @user.save
      redirect_to root_path
      current_user
    else
      redirect_to :back
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/raitings_helper.rb
module RaitingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.erb
<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= comment.user.name %></td>
      <td><%= comment.text %></td>
      <td><%= link_to 'Удалить комментарий', [comment.post, comment], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  </tbody>
</table>

app/views/comments/_form_for_comments.erb
<%= form_for([@post, @post.comments.build], remote: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('<%= j render @post.comments %>').appendTo('.comments_block');
$('#new_comment').remove();
$(location.reload());

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form_for_comments', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Index</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p id="notice"><%= notice %></p>

  <div class = "flex-container">
    <div class = "menu">
      <p>
        <%= link_to 'To index', pages_index_path %>
      </p>
      <p class="nav">
        <%= link_to 'To posts', posts_path %>
      </p>
      <%unless current_user%>
        <p>
          <%= link_to 'Registration', registration_path %>
        </p>
        <p>
          <%= link_to 'Log In', sessions_login_path %>
        </p>
      <%else%>
        <p>
          <%= link_to 'Log Out', sessions_logout_path %>
        </p>
      <%end%>
    </div>

    <div class ="user_name">
      <%= image_tag avatar_url(current_user) if current_user%>
      <%= current_user.name if current_user%>
    </div>

    <div class = "inf">
      <%= yield %>
    </div>
  </div>

  </body>
</html>

app/views/pages/index.html.erb
<h1>Test Blog</h1>

app/views/posts/_form.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <% @user = User.find(id = post.user_id)%>
  <td><%= image_tag post.image_url(:thumb) unless post.image.blank? if post.image %></td>
  <td><%= @user.name%></td>
  <td><%= post.title %></td>
  <td><%= post.body %></td>
  <td><%= link_to 'Show', post %></td>
  <td><%= link_to 'Edit', edit_post_path(post) if user_author(post.user)%></td>
  <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } if user_author(post.user)%></td>
  <td><%= link_to 'Like',like_path(id: post), remote: true %></td>
  <td><%= post.rating %></td>
  <td><%= link_to 'Dislike', dislike_path(id: post), remote: true %> </td>
</tr>

app/views/posts/best.html.erb
<h1>Best Posts</h1>

<table>

  <thead>
  <tr>
    <th></th>
    <th>Author</th>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>


  <% @post.each do |post| %>
    <tr>
      <% @user = User.find(id = post.user_id)%>
      <td><%= image_tag post.image_url(:thumb) unless post.image.blank? if post.image %></td>
      <td><%= @user.name%></td>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
    </tr>

  <% end %>
  </tbody>
</table>

app/views/posts/create.js.erb
$('table tbody').before('<%= j render partial: 'post', locals: {post: @post}%>');
$('#new_post').remove();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div id = "header"> <h1>Posts</h1> </div>

<table>

  <thead>
    <tr>
      <th></th>
      <th>Author</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>


<%= link_to 'Best posts', best_path%>
<div id = "new_post"> <%= link_to 'New Post', new_post_path, id: 'new_post_link', remote: true if current_user%> </div>

app/views/posts/new.js.erb
$('#new_post_link').after('<%= j render 'form'%>');

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<%= image_tag @post.image if @post.image%>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<h2>Комментарии:</h2>
<%= render @post.comments %>

<h2>Добавить комментарий:</h2>
<%= render 'comments/form_for_comments' %>

<%= link_to 'Edit', edit_post_path(@post) if user_author(@post.user)%> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>Registration</h1>


<%= form_for(@user) do |f| %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>